#!/usr/bin/env python
# coding: utf-8

# In[8]:


import boto3

s3 = boto3.resource('s3', aws_access_key_id = 'AKIA2NU2RLLOFEURHC3F', aws_secret_access_key='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')

try:
        s3.create_bucket(Bucket='hw3cmu14848maki',CreateBucketConfiguration={'LocationConstraint':'us-west-2'})
except Exception as e:
        print(e)


# In[11]:


bucket = s3.Bucket("hw3cmu14848maki")
bucket.Acl().put(ACL='public-read')


# In[12]:


body = open('/Users/makima/Downloads/Exp1.csv', 'rb')


# In[13]:


o = s3.Object('hw3cmu14848maki', 'test').put(Body=body )


# In[14]:


s3.Object('hw3cmu14848maki', 'test').Acl().put(ACL='public-read')


# In[15]:


dyndb = boto3.resource('dynamodb',
region_name='us-west-2',
aws_access_key_id='AKIA2NU2RLLOFEURHC3F', aws_secret_access_key='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'
)


# In[20]:


try:
    table = dyndb.create_table(
            TableName='DataTable',
            KeySchema=[
                {
                    'AttributeName': 'PartitionKey',
                    'KeyType': 'HASH'
    }, {
                    'AttributeName': 'RowKey',
                    'KeyType': 'RANGE'
                }
            ],
            AttributeDefinitions=[
                {
                    'AttributeName': 'PartitionKey',
                    'AttributeType': 'S'
    }, {
                    'AttributeName': 'RowKey',
                    'AttributeType': 'S'
                },
            ],
            ProvisionedThroughput={
                'ReadCapacityUnits': 5,
                'WriteCapacityUnits': 5
            }
    )
except Exception as e:
    print (e)
    #if there is an exception, the table may already exist.
    table = dyndb.Table("DataTable")


# In[21]:


table.meta.client.get_waiter('table_exists').wait(TableName='DataTable')


# In[22]:


print(table.item_count)


# In[23]:


import csv


# In[51]:


with open('/Users/makima/Downloads/experiments.csv', 'r') as csvfile: 
    csvf = csv.reader(csvfile, delimiter=',', quotechar='|')
    for item in csvf:
        print(item)
        if item[3]=='Concentration':
          continue
        body = open('/Users/makima/Downloads/datafiles/'+item[4], 'rb') 
        s3.Object('hw3cmu14848maki', item[3]).put(Body=body )
        md = s3.Object('hw3cmu14848maki', item[3]).Acl().put(ACL='public-read')
        url = " https://s3-us-west-2.amazonaws.com/hw3cmu14848maki/"+item[4] 
        metadata_item = {'PartitionKey': item[0], 'RowKey': item[1],
        'description' : item[4], 'date' : item[2], 'url':url}
        try: 
            table.put_item(Item=metadata_item)
        except:
            print("item may already be there or another failure")


# In[53]:


response = table.get_item(
    Key={
        'PartitionKey': '1',
        'RowKey': '-1'
    }
)
item = response['Item']
print(item)


# In[54]:


response


# In[ ]:




